export const AUTH_USER_INIT = 'AUTH_USER_INIT';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const AUTH_USER_END = 'AUTH_USER_END';

export const GET_USER_INIT = 'GET_USER_INIT';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_END = 'GET_USER_END';

export const GET_ACCOUNT_INIT = 'GET_ACCOUNT_INIT';
export const GET_ACCOUNT_ERROR = 'GET_ACCOUNT_ERROR';
export const GET_ACCOUNT_END = 'GET_ACCOUNT_END';