export const SYMBOLS_INIT = 'SYMBOLS_INIT';
export const SYMBOLS_ERROR = 'SYMBOLS_ERROR';
export const SYMBOLS_END = 'SYMBOLS_END';

export const WATCHLIST_INIT = 'WATCHLIST_INIT';
export const WATCHLIST_ERROR = 'WATCHLIST_ERROR';
export const WATCHLIST_END = 'WATCHLIST_END';

export const UPDATE_INIT = 'UPDATE_INIT';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_END = 'UPDATE_END';
