export const GET_SYMBOLS_INIT = 'GET_SYMBOLS_INIT';
export const GET_SYMBOLS_ERROR = 'GET_SYMBOLS_ERROR';
export const GET_SYMBOLS_END = 'GET_SYMBOLS_END';

export const GET_WATCHLIST_INIT = 'GET_WATCHLIST_INIT';
export const GET_WATCHLIST_ERROR = 'GET_WATCHLIST_ERROR';
export const GET_WATCHLIST_END = 'GET_WATCHLIST_END';

export const UPDATE_WATCHLIST_INIT = 'UPDATE_WATCHLIST_INIT';
export const UPDATE_WATCHLIST_ERROR = 'UPDATE_WATCHLIST_ERROR';
export const UPDATE_WATCHLIST_END = 'UPDATE_WATCHLIST_END';