export const SYMBOL_SEARCH_START = 'SYMBOL_SEARCH_START';
export const SYMBOL_SEARCH_SUCCESS = 'SYMBOL_SEARCH_SUCCESS';
export const SYMBOL_SEARCH_ERROR = 'SYMBOL_SEARCH_ERROR';

export const GET_WATCHLIST_START = 'GET_WATCHLIST_START';
export const GET_WATCHLIST_SUCCESS = 'GET_WATCHLIST_SUCCESS';
export const GET_WATCHLIST_ERROR = 'GET_WATCHLIST_ERROR';

export const ADD_SYMBOL_TO_WATCHLIST_START = 'ADD_SYMBOL_TO_WATCHLIST_START';
export const ADD_SYMBOL_TO_WATCHLIST_SUCCESS = 'ADD_SYMBOL_TO_WATCHLIST_SUCCESS';
export const ADD_SYMBOL_TO_WATCHLIST_ERROR = 'ADD_SYMBOL_TO_WATCHLIST_ERROR';

export const REMOVE_SYMBOL_FROM_WATCHLIST_START = 'REMOVE_SYMBOL_FROM_WATCHLIST_START';
export const REMOVE_SYMBOL_FROM_WATCHLIST_SUCCESS = 'REMOVE_SYMBOL_FROM_WATCHLIST_SUCCESS';
export const REMOVE_SYMBOL_FROM_WATCHLIST_ERROR = 'REMOVE_SYMBOL_FROM_WATCHLIST_ERROR';

export const GET_SYMBOL_CHARTS_START = 'GET_SYMBOL_CHARTS_START';
export const GET_SYMBOL_CHARTS_SUCCESS = 'GET_SYMBOL_CHARTS_SUCCESS';
export const GET_SYMBOL_CHARTS_ERROR = 'GET_SYMBOL_CHARTS_ERROR';

export const GET_SYMBOL_NEWS_START = 'GET_SYMBOL_NEWS_START';
export const GET_SYMBOL_NEWS_SUCCESS = 'GET_SYMBOL_NEWS_SUCCESS';
export const GET_SYMBOL_NEWS_ERROR = 'GET_SYMBOL_NEWS_ERROR';

export const INVALIDATE_NEWS = 'INVALIDATE_NEWS';
