export const GET_SYMBOL_INIT = 'GET_SYMBOL_INIT';
export const GET_SYMBOL_ERROR = 'GET_SYMBOL_ERROR';
export const GET_SYMBOL_END = 'GET_SYMBOL_END';

export const GET_CHARTS_INIT = 'GET_CHARTS_INIT';
export const GET_CHARTS_ERROR = 'GET_CHARTS_ERROR';
export const GET_CHARTS_END = 'GET_CHARTS_END';

export const GET_NEWS_INIT = 'GET_NEWS_INIT';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';
export const GET_NEWS_END = 'GET_NEWS_END';

export const OPEN_SYMBOL = 'OPEN_SYMBOL';
export const CLOSE_SYMBOL = 'CLOSE_SYMBOL';
